#!/bin/sh

set -e

if [ $# -ne 1 ]; then
  echo "Usage: $0 <ELF FILE>"
  exit 1
fi

OCD_DIR=$(brew --prefix openocd)
OCD_CFG_DIR=${OCD_DIR}/share/openocd/scripts

openocd -s ${OCD_CFG_DIR} -f interface/cmsis-dap.cfg -f target/tz10xx.cfg &
OCD_PID=$!

sleep 1
if ! kill -0 ${OCD_PID} > /dev/null 2>&1; then
  echo "Failed to launch openocd..."
  exit 1
fi

${TOOL_DIR}/arm-none-eabi-gdb -ex "target remote localhost:3333" -ex "monitor reset init" $1

kill ${OCD_PID} > /dev/null 2>&1 || echo "OpenOCD is already finished"
echo "debugger finished."
